#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import data_simulation as simulate
import seaborn as sns
import random
import matplotlib.pyplot as plt
import os
import pickle

os.chdir("/Users/andour/Google Drive/projects/Dissertation")
# Let us create a simulation, plot two of the selections and pickle the data
# There are seeds set so this should be reproducible
# %%


simulated_data = simulate.Noisy_logistic_generator(1000)
random.seed(31)
example = simulated_data[int(random.uniform(0, len(simulated_data)))]


plt.figure(figsize=(8,3))
sns.set_style("ticks")
plt.plot(example[:,0], example[:,1], sns.xkcd_rgb["pale red"], lw=1)
plt.title("Example of simulated logistic signal with Gaussian error")
plt.xlabel("Time")
plt.ylabel("Count")

# %%
plt.savefig("Example of generated data.png")
plt.show()
file = open("simulated_data_1000", "wb")
pickle.dump(simulated_data, file)
file.close

